language: python
python: "3.6"
sudo: false
cache: pip
install:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -vv
# command to run tests
script:
- poetry run python -u -m unittest discover tests

env:
  - JENKINS_USER_API_TOKEN="blablabla"
  - JENKINS2_USER_API_TOKEN="yaddayaddayadda"
  - JENKINS_JOB_TOKEN="abc123XYZ"
  - GITHUB_TOKEN="MEH-123"
  - PYTHONPATH="./qabot"
