language: python
python: "3.6"
sudo: false
cache: pip
install:
  - pip install -r requirements.txt
# command to run tests
script:
- export GITHUB_TOKEN="MEH-123"
- cd qabot
- python -m unittest discover ../tests
